type Token {
  token: String!
}

type User {
  _id: ID
  email: String
  name: String
  role: String
}

type Query {
  getUser: User
}

type Mutation {
  setUser(
    email: String!
    name: String!
    password: String!
    role: String!
  ): Boolean!
  userAuthentication(email: String!, password: String!): Token!
}
