type Order {
  _id: ID
  items: [OrderItem]!
  total: Float!
  createdAt: String
  clientId: ID!
  status: OrderStatus
  paymentStatus: PaymentStatus
  deliveryStatus: DeliveryStatus
  sellerId: ID
  contextId: ID
  deliveryCost: Float
}

type OrderItem {
  productId: ID!
  quantity: Int
  sellingPriceAtSale: Float
  purchasePriceAtSale: Float
}

enum OrderStatus {
  PENDING
  COMPLETED
  ACTIVE
  CANCELLED
}

enum PaymentStatus {
  PENDING
  PAID
  REFUNDED
}

enum DeliveryStatus {
  PENDING
  SENT
  COMPLETE
}

type Query {
  getOrderClient(clientId: ID!): [Order]!
  getAllOrders(limit: Int, offset: Int, date: String): [Order]!
  getOrder(_id: ID!): Order!
  totalOrders: Int
}

input OrderItemInput {
  productId: ID!
  quantity: Int
}

input OrderInput {
  _id: ID
  items: [OrderItemInput]!
  total: Float!
  createdAt: String
  clientId: ID!
  status: OrderStatus
  paymentStatus: PaymentStatus
  deliveryStatus: DeliveryStatus
  sellerId: ID!
  contextId: ID
  deliveryCost: Float
}

type Mutation {
  setOrder(input: OrderInput!): Boolean!
  updateOrder(input: OrderInput!): Boolean!
  deleteOrder(_id: ID!): Boolean!
}
