type Client {
	_id: ID
	nombre: String!
	apellido: String!
	empresa: String!
	emails: [Email]
	edad: Int!
	tipo: TipoCliente!
	pedidos: [Pedido]!
}

type Pedido {
	producto: String
	precio: Int
}

type Email {
	email: String
}

enum TipoCliente {
	BASICO
	PREMIUM
}

type Query {
	getClient(_id: ID!): Client!
	getAllClients(limite:Int): [Client]
}

#Inputs Mutation!
input iPedido {
	producto: String
	precio: Int
}

input iEmail{
	email:String
}

input iClient {
	nombre: String!
	apellido: String!
	empresa: String!
	emails: [iEmail]
	edad: Int!
	tipo: TipoCliente!
	pedidos: [iPedido]
}

type Mutation {
	#Crear
	setClient(input: iClient): Boolean!
	#Update
	updateClient(_id:ID!, input:iClient):Boolean!
	#Delete
	deleteClient(_id:ID!):Boolean!
}
