type Client {
  _id: ID
  firstName: String!
  lastName: String!
  address: String!
  whatsapp: String!
  age: Int!
  type: ClientType!
  sellerId: ID
}

enum ClientType {
  BASIC
  CONCURRENT
  PREMIUM
}

type Query {
  getClient(_id: ID!): Client!
  getAllClients(limit: Int, offset: Int, sellerId: ID): [Client]!
  totalClients(sellerId: ID): Int
}

input ClientInput {
  _id: ID
  firstName: String!
  lastName: String!
  address: String!
  whatsapp: String!
  age: Int!
  sellerId: ID
}

type Mutation {
  setClient(input: ClientInput!): Boolean!
  updateClient(input: ClientInput!): Boolean!
  deleteClient(_id: ID!): Boolean!
}
