type Product {
  _id: ID
  name: String!
  price: Float!
  stock: Int!
}

type Query {
  getAllProducts(limit: Int, offset: Int): [Product]!
  getProduct(_id: ID!): Product!
  totalProducts: Int
}

input ProductInput {
  _id: ID
  name: String!
  price: Float!
  stock: Int!
}

type Mutation {
  setProduct(input: ProductInput!): Boolean!
  updateProduct(input: ProductInput!): Boolean!
  deleteProduct(_id: ID!): Boolean!
}
