type DatabaseStatus {
  clientsCount: Int!
  testingClientsCount: Int!
  productsCount: Int!
  testingProductsCount: Int!
  ordersCount: Int!
  testingOrdersCount: Int!
  usersCount: Int!
  testingUsersCount: Int!
}

type SystemConfig {
  id: ID!
  rentalsEnabled: Boolean!
}

type Query {
  getDatabaseStatus: DatabaseStatus!
  getSystemConfig: SystemConfig!
}

type Mutation {
  seedDatabase: Boolean!
  wipeDatabase: Boolean!
  updateSystemConfig(rentalsEnabled: Boolean!): SystemConfig!
}
